### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by magicknot** [ist-dsi/mattermost-cookbook#27]
Currently, Travis CI is failing giving the output:

```
$ eval "$(chef shell-init bash)"
Traceback (most recent call last):
	3: from /usr/bin/chef:261:in `<main>'
	2: from /opt/chefdk/embedded/lib/ruby/2.5.0/rubygems/specification.rb:1055:in `find_by_name'
	1: from /opt/chefdk/embedded/lib/ruby/2.5.0/rubygems/dependency.rb:322:in `to_spec'
/opt/chefdk/embedded/lib/ruby/2.5.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'chef-dk' (>= 0) among 37 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/travis/.rvm/gems/ruby-2.4.1:/home/travis/.rvm/gems/ruby-2.4.1@global', execute `gem env` for more information
$ chef --version
Traceback (most recent call last):
	3: from /usr/bin/chef:261:in `<main>'
	2: from /opt/chefdk/embedded/lib/ruby/2.5.0/rubygems/specification.rb:1055:in `find_by_name'
	1: from /opt/chefdk/embedded/lib/ruby/2.5.0/rubygems/dependency.rb:322:in `to_spec'
/opt/chefdk/embedded/lib/ruby/2.5.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'chef-dk' (>= 0) among 37 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/travis/.rvm/gems/ruby-2.4.1:/home/travis/.rvm/gems/ruby-2.4.1@global', execute `gem env` for more information
The command "chef --version" failed and exited with 1 during .
```

**Comment by magicknot** [comment]
It appears it was a problem upstream.
